apiVersion: v2
description: Helm chart for Java application/service deploying
name: user-settings-service-api
version: 0.0.1
appVersion: 0.0.1
sources:
    - https://github.com
maintainers:
    - name: MDDA-BPD
type: application
keywords:
    - Java
home: https://www.epam.com
