apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-settings-service-api.name" . }}
  labels:
    {{- include "user-settings-service-api.labels" . | nindent 4 }}
spec:
  ports:
    - name: api
      {{- if .Values.service.type }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      {{- end }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    {{- include "user-settings-service-api.selectorLabels" . | nindent 4 }}
  type: {{ default "ClusterIP" (.Values.service.type | quote) }}